version: "2.4"

services:
  app:
    build: &default-build
      context: ./app
      args:
        - http_proxy
        - https_proxy
    runtime: nvidia
    volumes:
      - ./app:/srv
      - ./store:/store

  filebrowser:
    build:
      <<: *default-build
      context: ./filebrowser
    command: --noauth
    volumes:
      - ./store:/srv
      - ./filebrowser/filebrowser.json:/.filebrowser.json
    ports:
      - "${WEB_PORT}:80"
