version: "2.4"

services:
  app:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    runtime: nvidia
    volumes:
      - ./app:/srv
      - ./store:/store

  web:
    build:
      context: ./web
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./store:/public
    ports:
      - "${WEB_PORT}:80"
